version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/my-app

    steps:
      - checkout

      - run:
          name: Set up Java
          command: echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $BASH_ENV

      - run:
          name: Build and Test
          command: mvn clean test
